### PR TITLE
`{{did-insert}}`, `{{did-update}}` and `{{will-destroy}}` API docs

### PR DESCRIPTION
**Pull request by GavinJoyce**
part of https://github.com/emberjs/ember-render-modifiers/issues/2

### CODE REVIEW

**Comment by rwjblue** [comment]
Also, I'm happy to land PR's like this iteratively...

**Comment by GavinJoyce** [comment]
> I think we should also mention that the function is not bound to the template context by default, and show how the user might do that (e.g. via action or using ember-bind-helper)

I've added a short section on using `action` to bind the component context. It would be nicer to provide a simple example of when to use this, I couldn't think of one though.  Perhaps you have an example that I could borrow? 

> I'm happy to land PR's like this iteratively...

👍This PR is now focused on documenting `{{did-insert}}`. I'll follow up with docs for the other two once we're happy with this one

**Comment by GavinJoyce** [comment]
Thanks, I tried to keep it as simple as possible so I added the following example:

---

By default, the executed function will be unbound. If you would like to access the component context in your function, use the `action` helper as follows:

```handlebars
<div {{did-insert (action this.incrementCount)}}>first</div>
<div {{did-insert (action this.incrementCount)}}>second</div>

<p>{{this.count}} elements were rendered</p>
```

```js
export default Component.extend({
  @tracked count = 0;

  incrementCount() {
    this.count++;
  }
});
```

**Comment by GavinJoyce** [comment]
I've added docs for `{{did-update}}` and `{{will-destroy}}` too

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
