### PR TITLE
Add link to video with examples of how to migrate away

### PR DESCRIPTION
**Pull request by achambers**
[RENDERED](https://github.com/achambers/ember-render-modifiers/blob/patch-1/README.md)

I recently gave a talk at EmberFest to describe the rationale and history of these modifiers, why they are considered an anti-pattern today and, most importantly, what the alternatives are for migrating away from them using concrete examples.

This talk is the culmination of many conversations and pairing sessions with engineers educating them on this info which they don't get from the README, so this seems like the perfect place to link to the talk.

### CODE REVIEW

**Comment by achambers** [comment]
Any thoughts on this @rwwagner90 ?

**Comment by rwwagner90** [comment]
@achambers I definitely need to check out this talk! I personally find these modifiers very useful though, so unsure how much we want to recommend against them.

**Comment by achambers** [comment]
> @achambers I definitely need to check out this talk! I personally find these modifiers very useful though, so unsure how much we want to recommend against them.

Coolio. Have a watch and see what you think. The README of this repo says they are an anti-pattern and you should generally re-think your approach if you're reaching for them but gives very little context on _how_ to do that or _what_ to do instead. The talk linked does exactly that so I see it as giving more clarity to what already exists in the README.

Give the talk a watch and then let's discuss.

**Comment by achambers** [comment]
Any further thoughts on this @rwwagner90 . This is a topic I've had so many conversations about with so many engineers. Would be great to get this on the README to make things clearer for folks.

**Comment by chriskrycho** [comment]
@RobbieTheWagner the text that is there is there for a reason; multiple folks on Framework (including @rwjblue and me) *helped draft it*. We should get this merged and get @achambers' talk and recommendations in front of the community even more broadly!

---

If I had my druthers, we would deprecate these entirely; custom modifiers are *always* better for purpose, and in a `<template>` world the utility of this package drops from zero to *negative*—you can write a custom modifier *right next to* the component and get all the benefits of these without the "lifecycle hook" mentality they encourage.

**Comment by chriskrycho** [comment]
Going to go ahead and merge this; it is now *even longer* that we have been emphasizing that folks should not use these.

**Pull request merged**
